---
seminars:
  - "Отдел Т: Эксперименты на токамаках"
  - "Инженерно-физические проблемы термоядерных реакторов"
  - "Теория магнитного удержания плазмы"
  - "Инженерно-физический семинар по токамакам"

hashtags: 
  - "#ОТ"
  - "#ИФП"
  - "#ТМУ"
  - "#ИФС"