---
seminars:
  - "Отдел Т: Эксперименты на токамаках"
  - "Инженерно-физические проблемы термоядерных реакторов"
  - "Теория магнитного удержания плазмы"
  - "Инженерно-физический семинар по токамакам"

hashtags: 
  - "#ОТ"
  - "#ИФП"
  - "#ТМУ"
  - "#ИФС"

hello_text: "Приветствую! Я умею присылать сообщения о объявленных семинарах. \nЕще можно вывести сообщения о последних семинарах в чат. Для этого воспользуйтесь командой /last и выберите интересующие вас тематики. \nЕсли хочется больше семинаров, можно ввести /last N для вывода N последних семинаров. \nТакже я могу искать записи, содержащие интересующий вас текст. Для этого введите /find и свой поисковый запрос в следующем сообщении. \nЕсли вы хотите получать уведомления о новых семинарах в личные сообщения, воспользуйтесь командой /subscribe и /unsubscribe, чтобы отменить подписку."