services:
  seminar-bot:
        container_name: seminar-bot
        restart: unless-stopped
        logging:
            options:
                max-size: 1m
        environment:
          - bot_token=CHANGEME
          - chat_id=CHANGEME
          - admin_id=CHANGEME
          - timer=1
          - rate_limit=0.5
          - silent_start=True
        volumes:
            # - ./:/app/news
            - /etc/localtime:/etc/localtime:ro
        image: docker.io/library/seminar_bot:0.7.9