services:
  seminar-bot:
        container_name: seminar-bot
        restart: unless-stopped
        deploy:
          resources:
            limits:
              cpus: '1.0'
              memory: 250M
#        logging:
#            options:
#                max-size: 1m
        environment:
          - bot_token=${token}
          - chat_id=${chat_id}
          - admin_id=${admin_id}
          - moderators_id=${mods_list}
          - timer=1
          - rate_limit=0.5
          - silent_mode=False
          - check_debug=False
          - request_target=${request_chat_id}
        volumes:
            - ./nrcki-bot/data:/app/data
            - ./nrcki-bot/config:/app/config
        image: mrboshi/seminar_bot:0.12.0