services:
  seminar-bot:
        container_name: seminar-bot
        build:
          context: .
          dockerfile: Dockerfile
        restart: unless-stopped
        logging:
            options:
                max-size: 1m
        ports:
          - 8080:8080
        environment:
          - bot_token=CHANGEME
          - chat_id=CHANGEME
          - admin_id=CHANGEME
          - moderators_id=CHANGEME
          - ssl_sert=/app/cert/fullchain.pem
          - ssl_privkey=/app/privkey.pem
          - webhook_port=8080
          # - timer=1
          # - rate_limit=0.5
          # - silent_start=True
        volumes:
            # - ./:/app/news
            # - ./letsencrypt:/app/cert:ro
        image: seminar_bot:0.9.0