services:
  seminar-bot:
        container_name: seminar-bot
        restart: unless-stopped
        logging:
            options:
                max-size: 1m
        ports:
          - 8443:8443
        environment:
          - bot_token=CHANGEME
          - chat_id=CHANGEME
          - admin_id=CHANGEME
          - moderators_id=CHANGEME
          - ssl_sert=/app/cert/live/npm-14/fullchain.pem
          - ssl_privkey=/app/cert/live/npm-14/privkey.pem
          - webhook_port=8443
          # - timer=1
          # - rate_limit=0.5
          # - silent_start=True
        volumes:
            # - ./:/app/news
            # - ./letsencrypt:/app/cert:ro
        image: docker.io/library/seminar_bot:0.8.1